"""REST API for the Hosur Services frontend, mounted under /api.

Ids are generated by the client so the UI can update optimistically and the
server stays in step without a round trip to learn the new id.
"""

import os
from functools import lru_cache
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from pydantic.alias_generators import to_camel

from hosur.store import Store

DEFAULT_DB_PATH = Path(__file__).resolve().parent.parent / "data" / "hosur.db"


@lru_cache
def get_store() -> Store:
    return Store(os.getenv("HOSUR_DB_PATH", DEFAULT_DB_PATH))


class CamelModel(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    def dump(self) -> dict:
        return self.model_dump(by_alias=True)


NonEmpty = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


class ServiceIn(CamelModel):
    id: NonEmpty
    name: NonEmpty
    tamil: NonEmpty
    category: NonEmpty


class ProviderIn(CamelModel):
    id: NonEmpty
    service_id: NonEmpty
    name: NonEmpty
    phone: NonEmpty
    rating: float = Field(ge=1, le=5)
    experience: NonEmpty
    area: str | None = None


class ProviderAreaIn(CamelModel):
    area: str | None = None


class ReviewIn(CamelModel):
    id: NonEmpty
    provider_id: NonEmpty
    user_name: NonEmpty
    rating: float = Field(ge=1, le=5)
    comment: NonEmpty
    created_at: str | None = None


class NewsItemIn(CamelModel):
    id: NonEmpty
    badge: NonEmpty
    area: NonEmpty
    title: NonEmpty
    summary: NonEmpty


class FeedPostIn(CamelModel):
    id: NonEmpty
    author: NonEmpty
    handle: NonEmpty
    location: NonEmpty
    title: NonEmpty
    caption: NonEmpty
    accent: NonEmpty
    tag: NonEmpty
    created_at: str | None = None


class LikeIn(CamelModel):
    user_id: NonEmpty


class AskedForIn(CamelModel):
    query: NonEmpty


router = APIRouter(prefix="/api")


def _created(result, conflict: str):
    if result is None:
        raise HTTPException(status_code=409, detail=conflict)
    return result


@router.get("/state")
def get_state(store: Store = Depends(get_store)):
    return store.get_state()


@router.post("/services", status_code=201)
def add_service(service: ServiceIn, store: Store = Depends(get_store)):
    return _created(store.add_service(service.dump()), "A service with this id already exists.")


@router.post("/providers", status_code=201)
def add_provider(provider: ProviderIn, store: Store = Depends(get_store)):
    return _created(store.add_provider(provider.dump()), "Unknown service, or this provider is already listed for it.")


@router.patch("/providers/{provider_id}")
def update_provider(provider_id: str, update: ProviderAreaIn, store: Store = Depends(get_store)):
    provider = store.update_provider_area(provider_id, update.area)
    if provider is None:
        raise HTTPException(status_code=404, detail="Provider not found.")
    return provider


@router.delete("/providers/{provider_id}", status_code=204)
def delete_provider(provider_id: str, store: Store = Depends(get_store)):
    if not store.delete_provider(provider_id):
        raise HTTPException(status_code=404, detail="Provider not found.")


@router.post("/reviews", status_code=201)
def add_review(review: ReviewIn, store: Store = Depends(get_store)):
    return _created(store.add_review(review.dump()), "Unknown provider, or this review already exists.")


@router.post("/news", status_code=201)
def add_news_item(item: NewsItemIn, store: Store = Depends(get_store)):
    return _created(store.add_news_item(item.dump()), "A news item with this id already exists.")


@router.post("/feed", status_code=201)
def add_feed_post(post: FeedPostIn, store: Store = Depends(get_store)):
    return _created(store.add_feed_post(post.dump()), "A post with this id already exists.")


@router.post("/feed/{post_id}/like")
def like_post(post_id: str, like: LikeIn, store: Store = Depends(get_store)):
    post = store.like_post(post_id, like.user_id)
    if post is None:
        raise HTTPException(status_code=404, detail="Post not found.")
    return post


@router.post("/asked-for", status_code=201)
def add_asked_for(entry: AskedForIn, store: Store = Depends(get_store)):
    return store.add_asked_for(entry.query.strip())
