import type { RegistrationLanguage } from "./api/hosur";

export const registrationLanguages: { id: RegistrationLanguage; label: string }[] = [
  { id: "ta", label: "தமிழ்" }, { id: "te", label: "తెలుగు" }, { id: "kn", label: "ಕನ್ನಡ" }, { id: "en", label: "English" },
];

export const registrationText = {
  en: {
    title: "Join as a service provider", intro: "Work in Hosur? Register here. Our admin will review your details before your listing goes live.",
    back: "Back to services", language: "Choose your language", name: "Your name", phone: "Mobile / WhatsApp number",
    phoneHelp: "Enter a 10-digit Indian mobile number. +91 is also accepted.", services: "What services do you offer?",
    search: "Search services", serviceHelp: "Choose up to 10 services. You can select more than one.", noMatches: "No matching services. Try a different search.",
    area: "Based in (locality)", areaHelp: "Enter your locality, not your full home address. Customers can see your base location.",
    experience: "Experience (optional)", experienceHint: "For example: 5 years",
    consent: "I agree that my name, services, locality and experience may be listed after approval. Hosur Services may contact me to verify these details and share my phone number with customers to contact me for work.",
    submit: "Submit registration", saving: "Submitting...", loading: "Loading services...", loadError: "Services could not be loaded. Check your connection and retry.",
    retry: "Retry", noServices: "Registration is unavailable because no services are listed yet. Please check back later.",
    missing: "Enter your name and locality, select at least one service, and give consent.", phoneError: "Enter a valid 10-digit Indian mobile number.",
    tooMany: "You can select up to 10 services.", duplicate: "An application or listing already exists for this number and one of these services. Do not submit again while it is being reviewed.",
    invalid: "Some details could not be accepted. Check the fields and selected services, then retry.", failed: "Registration could not be confirmed. Your details are still here; please retry. You are not listed until admin approval.",
    success: "Registration received", pending: "Your application is pending admin approval. Your listing will appear only after approval. We may call you to confirm your details.",
    reference: "Application reference", noFee: "No password or document upload needed.", selected: "Selected services",
  },
  ta: {
    title: "சேவை வழங்குநராகப் பதிவு செய்யுங்கள்", intro: "ஹோசூரில் வேலை செய்கிறீர்களா? இங்கே பதிவு செய்யுங்கள். உங்கள் விவரங்களை நிர்வாகி சரிபார்த்து ஒப்புதல் அளித்த பிறகே பட்டியலில் சேர்க்கப்படும்.",
    back: "சேவைகளுக்குத் திரும்பவும்", language: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்", name: "உங்கள் பெயர்", phone: "மொபைல் / வாட்ஸ்அப் எண்",
    phoneHelp: "10 இலக்க இந்திய மொபைல் எண்ணை உள்ளிடவும். +91 உடனும் உள்ளிடலாம்.", services: "நீங்கள் என்ன சேவைகள் செய்கிறீர்கள்?",
    search: "சேவைகளைத் தேடுங்கள்", serviceHelp: "அதிகபட்சம் 10 சேவைகளைத் தேர்ந்தெடுக்கலாம். ஒன்றுக்கு மேற்பட்ட சேவைகளைத் தேர்வு செய்யலாம்.", noMatches: "சேவைகள் கிடைக்கவில்லை. வேறு சொல்லைத் தேடவும்.",
    area: "இருப்பிடம் (பகுதி)", areaHelp: "உங்கள் பகுதியை மட்டும் உள்ளிடவும்; முழு வீட்டு முகவரி வேண்டாம். வாடிக்கையாளர்கள் உங்கள் பகுதியைப் பார்க்கலாம்.",
    experience: "அனுபவம் (விருப்பம்)", experienceHint: "எடுத்துக்காட்டு: 5 ஆண்டுகள்",
    consent: "ஒப்புதலுக்குப் பிறகு என் பெயர், சேவைகள், பகுதி மற்றும் அனுபவம் பட்டியலில் காட்டப்படலாம் என்பதை ஏற்கிறேன். விவரங்களைச் சரிபார்க்க ஹோசூர் சர்வீசஸ் என்னைத் தொடர்புகொள்ளவும், வேலைக்காக வாடிக்கையாளர்கள் என்னைத் தொடர்புகொள்ள என் தொலைபேசி எண்ணைப் பகிரவும் அனுமதிக்கிறேன்.",
    submit: "பதிவை அனுப்பவும்", saving: "அனுப்பப்படுகிறது...", loading: "சேவைகள் ஏற்றப்படுகின்றன...", loadError: "சேவைகளை ஏற்ற முடியவில்லை. இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    retry: "மீண்டும் முயற்சி", noServices: "இன்னும் சேவைகள் பட்டியலிடப்படாததால் பதிவு செய்ய முடியவில்லை. பின்னர் முயற்சிக்கவும்.",
    missing: "பெயர், பகுதி, குறைந்தது ஒரு சேவை மற்றும் ஒப்புதல் தேவை.", phoneError: "சரியான 10 இலக்க இந்திய மொபைல் எண்ணை உள்ளிடவும்.",
    tooMany: "அதிகபட்சம் 10 சேவைகளைத் தேர்ந்தெடுக்கலாம்.", duplicate: "இந்த எண்ணுக்கும் தேர்ந்தெடுத்த சேவைகளில் ஒன்றுக்கும் ஏற்கனவே விண்ணப்பம் அல்லது பதிவு உள்ளது. பரிசீலனையில் இருக்கும்போது மீண்டும் அனுப்ப வேண்டாம்.",
    invalid: "சில விவரங்கள் ஏற்கப்படவில்லை. விவரங்களையும் சேவைகளையும் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", failed: "பதிவை உறுதிப்படுத்த முடியவில்லை. உங்கள் விவரங்கள் இங்கே உள்ளன; மீண்டும் முயற்சிக்கவும். நிர்வாகி ஒப்புதல் அளிக்கும் வரை பட்டியலில் காட்டப்படாது.",
    success: "பதிவு பெறப்பட்டது", pending: "உங்கள் விண்ணப்பம் நிர்வாகியின் ஒப்புதலுக்காகக் காத்திருக்கிறது. ஒப்புதலுக்குப் பிறகே பட்டியலில் காட்டப்படும். விவரங்களை உறுதிப்படுத்த உங்களை அழைக்கலாம்.",
    reference: "விண்ணப்ப எண்", noFee: "கடவுச்சொல் அல்லது ஆவணப் பதிவேற்றம் தேவையில்லை.", selected: "தேர்ந்தெடுத்த சேவைகள்",
  },
  te: {
    title: "సేవలందించే వ్యక్తిగా నమోదు చేసుకోండి", intro: "హోసూరులో పని చేస్తున్నారా? ఇక్కడ నమోదు చేసుకోండి. నిర్వాహకులు మీ వివరాలను పరిశీలించి ఆమోదించిన తర్వాతే మీ పేరు జాబితాలో కనిపిస్తుంది.",
    back: "సేవలకు తిరిగి వెళ్ళండి", language: "మీ భాషను ఎంచుకోండి", name: "మీ పేరు", phone: "మొబైల్ / వాట్సాప్ నంబర్",
    phoneHelp: "10 అంకెల భారతీయ మొబైల్ నంబర్ ఇవ్వండి. +91తో కూడా ఇవ్వవచ్చు.", services: "మీరు ఏ సేవలు అందిస్తారు?",
    search: "సేవలను వెతకండి", serviceHelp: "గరిష్ఠంగా 10 సేవలు ఎంచుకోవచ్చు. ఒకటి కంటే ఎక్కువ ఎంచుకోవచ్చు.", noMatches: "సేవలు కనిపించలేదు. మరో పదంతో వెతకండి.",
    area: "మీ ప్రాంతం", areaHelp: "మీ ప్రాంతం పేరు ఇవ్వండి; పూర్తి ఇంటి చిరునామా వద్దు. కస్టమర్లు మీ ప్రాంతాన్ని చూడగలరు.",
    experience: "అనుభవం (ఐచ్ఛికం)", experienceHint: "ఉదాహరణ: 5 సంవత్సరాలు",
    consent: "ఆమోదం తర్వాత నా పేరు, సేవలు, ప్రాంతం మరియు అనుభవాన్ని చూపించడానికి అంగీకరిస్తున్నాను. వివరాలను నిర్ధారించడానికి హోసూర్ సర్వీసెస్ నన్ను సంప్రదించవచ్చు. పని కోసం కస్టమర్లు నన్ను సంప్రదించేందుకు నా ఫోన్ నంబర్ పంచుకోవడానికి అనుమతిస్తున్నాను.",
    submit: "నమోదు పంపండి", saving: "పంపుతోంది...", loading: "సేవలు లోడ్ అవుతున్నాయి...", loadError: "సేవలు లోడ్ కాలేదు. ఇంటర్నెట్ కనెక్షన్ చూసి మళ్ళీ ప్రయత్నించండి.",
    retry: "మళ్ళీ ప్రయత్నించండి", noServices: "ఇంకా సేవలు జాబితాలో లేవు కాబట్టి నమోదు అందుబాటులో లేదు. తర్వాత ప్రయత్నించండి.",
    missing: "మీ పేరు, ప్రాంతం, కనీసం ఒక సేవ మరియు సమ్మతి ఇవ్వండి.", phoneError: "సరైన 10 అంకెల భారతీయ మొబైల్ నంబర్ ఇవ్వండి.",
    tooMany: "గరిష్ఠంగా 10 సేవలు ఎంచుకోవచ్చు.", duplicate: "ఈ నంబర్ మరియు ఎంచుకున్న సేవల్లో ఒకదానికి ఇప్పటికే దరఖాస్తు లేదా నమోదు ఉంది. పరిశీలనలో ఉన్నప్పుడు మళ్ళీ పంపవద్దు.",
    invalid: "కొన్ని వివరాలు అంగీకరించబడలేదు. వివరాలు, సేవలు సరిచూసి మళ్ళీ ప్రయత్నించండి.", failed: "నమోదును నిర్ధారించలేకపోయాము. మీ వివరాలు ఇక్కడే ఉన్నాయి; మళ్ళీ ప్రయత్నించండి. నిర్వాహకుల ఆమోదం వరకు జాబితాలో కనిపించరు.",
    success: "నమోదు అందింది", pending: "మీ దరఖాస్తు నిర్వాహకుల ఆమోదం కోసం వేచి ఉంది. ఆమోదించిన తర్వాతే జాబితాలో కనిపిస్తుంది. వివరాలు నిర్ధారించడానికి మీకు కాల్ చేయవచ్చు.",
    reference: "దరఖాస్తు సంఖ్య", noFee: "పాస్‌వర్డ్ లేదా పత్రాల అప్‌లోడ్ అవసరం లేదు.", selected: "ఎంచుకున్న సేవలు",
  },
  kn: {
    title: "ಸೇವಾ ಪೂರೈಕೆದಾರರಾಗಿ ನೋಂದಾಯಿಸಿ", intro: "ಹೊಸೂರಿನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತೀರಾ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ. ನಿರ್ವಾಹಕರು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಅನುಮೋದಿಸಿದ ನಂತರವೇ ಪಟ್ಟಿಯಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತೀರಿ.",
    back: "ಸೇವೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ", language: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", name: "ನಿಮ್ಮ ಹೆಸರು", phone: "ಮೊಬೈಲ್ / ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ",
    phoneHelp: "10 ಅಂಕಿಯ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನೀಡಿ. +91 ಜೊತೆಯೂ ನೀಡಬಹುದು.", services: "ನೀವು ಯಾವ ಸೇವೆಗಳನ್ನು ನೀಡುತ್ತೀರಿ?",
    search: "ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ", serviceHelp: "ಗರಿಷ್ಠ 10 ಸೇವೆಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಬಹುದು. ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಆಯ್ಕೆ ಮಾಡಬಹುದು.", noMatches: "ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಬೇರೆ ಪದ ಬಳಸಿ ಹುಡುಕಿ.",
    area: "ನಿಮ್ಮ ಪ್ರದೇಶ", areaHelp: "ನಿಮ್ಮ ಪ್ರದೇಶದ ಹೆಸರು ನೀಡಿ; ಪೂರ್ಣ ಮನೆಯ ವಿಳಾಸ ಬೇಡ. ಗ್ರಾಹಕರು ನಿಮ್ಮ ಪ್ರದೇಶವನ್ನು ನೋಡಬಹುದು.",
    experience: "ಅನುಭವ (ಐಚ್ಛಿಕ)", experienceHint: "ಉದಾಹರಣೆ: 5 ವರ್ಷಗಳು",
    consent: "ಅನುಮೋದನೆಯ ನಂತರ ನನ್ನ ಹೆಸರು, ಸೇವೆಗಳು, ಪ್ರದೇಶ ಮತ್ತು ಅನುಭವವನ್ನು ಪಟ್ಟಿಯಲ್ಲಿ ತೋರಿಸಲು ಒಪ್ಪುತ್ತೇನೆ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಹೊಸೂರು ಸರ್ವೀಸಸ್ ನನ್ನನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು. ಕೆಲಸಕ್ಕಾಗಿ ಗ್ರಾಹಕರು ನನ್ನನ್ನು ಸಂಪರ್ಕಿಸಲು ನನ್ನ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಅನುಮತಿಸುತ್ತೇನೆ.",
    submit: "ನೋಂದಣಿ ಸಲ್ಲಿಸಿ", saving: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...", loading: "ಸೇವೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...", loadError: "ಸೇವೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", noServices: "ಇನ್ನೂ ಸೇವೆಗಳ ಪಟ್ಟಿಯಿಲ್ಲದ ಕಾರಣ ನೋಂದಣಿ ಲಭ್ಯವಿಲ್ಲ. ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    missing: "ಹೆಸರು, ಪ್ರದೇಶ, ಕನಿಷ್ಠ ಒಂದು ಸೇವೆ ಮತ್ತು ಒಪ್ಪಿಗೆ ನೀಡಿ.", phoneError: "ಸರಿಯಾದ 10 ಅಂಕಿಯ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನೀಡಿ.",
    tooMany: "ಗರಿಷ್ಠ 10 ಸೇವೆಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಬಹುದು.", duplicate: "ಈ ಸಂಖ್ಯೆ ಮತ್ತು ಆಯ್ಕೆ ಮಾಡಿದ ಸೇವೆಗಳಲ್ಲಿ ಒಂದಕ್ಕೆ ಈಗಾಗಲೇ ಅರ್ಜಿ ಅಥವಾ ನೋಂದಣಿ ಇದೆ. ಪರಿಶೀಲನೆಯಲ್ಲಿರುವಾಗ ಮತ್ತೆ ಸಲ್ಲಿಸಬೇಡಿ.",
    invalid: "ಕೆಲವು ವಿವರಗಳನ್ನು ಸ್ವೀಕರಿಸಲಾಗಲಿಲ್ಲ. ವಿವರಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", failed: "ನೋಂದಣಿಯನ್ನು ಖಚಿತಪಡಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಮ್ಮ ವಿವರಗಳು ಇಲ್ಲೇ ಇವೆ; ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ. ನಿರ್ವಾಹಕರ ಅನುಮೋದನೆ ಬರುವವರೆಗೆ ಪಟ್ಟಿಯಲ್ಲಿ ಕಾಣಿಸುವುದಿಲ್ಲ.",
    success: "ನೋಂದಣಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ", pending: "ನಿಮ್ಮ ಅರ್ಜಿ ನಿರ್ವಾಹಕರ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ. ಅನುಮೋದನೆಯ ನಂತರವೇ ಪಟ್ಟಿಯಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ. ವಿವರಗಳನ್ನು ಖಚಿತಪಡಿಸಲು ನಿಮಗೆ ಕರೆ ಮಾಡಬಹುದು.",
    reference: "ಅರ್ಜಿ ಸಂಖ್ಯೆ", noFee: "ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ ದಾಖಲೆಗಳ ಅಪ್‌ಲೋಡ್ ಅಗತ್ಯವಿಲ್ಲ.", selected: "ಆಯ್ಕೆ ಮಾಡಿದ ಸೇವೆಗಳು",
  },
} satisfies Record<RegistrationLanguage, Record<string, string>>;
